### ISSUE TITLE
Exceptions hiding (and now showing) devices

### ISSUE THREAD

**Issue by IslandJohn** [dixonte/HidVanguard#2]
I receive an error trying to disable a device, after which HidVanguard crashed, and now I cannot re-enable it since HidVanguard shows a different exception on launch and immediately exits.
![Screenshot (25)](https://user-images.githubusercontent.com/1694517/95588210-1f40e300-0a11-11eb-9c43-1922c5260ff1.png)
![Screenshot (26)](https://user-images.githubusercontent.com/1694517/95588211-20721000-0a11-11eb-84c6-f9797aeec95c.png)

**Comment by IslandJohn** [comment]
I uninstalled HidGuardian, which no longer causes issues for HidVanguard, but obviously hiding/showing does not actually work, amd HidVanguard still shows HidGuardian as Installed.

**Comment by dixonte** [comment]
Hi @IslandJohn, sorry it's been a little while.

Could you try installing HidGuardian again and try manually clearing out the AffectedDevices key in your registry?

1. Run regedit
2. Go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HidGuardian\Parameters
3. Double-click on AffectedDevices and delete all lines (or copy them elsewhere if you want to be safe; a text file on your desktop would do)

Then see if HidVanguard Config complains. If it does, I'll see if I can figure something out.

**Comment by IslandJohn** [comment]
The latest build from November seems to have fixed the exception issue.
