### ISSUE TITLE
Exception when trying to launch HidVanguard.config

### ISSUE THREAD

**Issue by vdubus** [dixonte/HidVanguard#4]
After removing my 2 × T.16000M joystick and putting 2 × VKB Gladiator NXT, I tried to switch HID Guardian to ignore these in place of the 2 before.

But, Vanguard would crash each time I was trying to update the config.

![HID Vanguard error](https://user-images.githubusercontent.com/185246/99148637-218a0300-2689-11eb-9fd6-a6c59cfb424e.PNG)

I am currently trying to uninstall everything and make a new clean installation.

**Comment by dixonte** [comment]
I looked into this. Seems the probable cause is the buffer I was passing to Windows to get device information was too small. I was lazy and assumed I'd allocated enough. This new version should ask Windows how big a buffer to allocate first. Let me know how you go with v1.0.2.0 please.

**Comment by vdubus** [comment]
`HidVanguard Config` do start now. 👍🏼
I will try to make Joystick Gremlin work again to check if it work to the end.

**Comment by vdubus** [comment]
This is working perfectly! 👌🏼
Thx for the fix.

**Comment by dixonte** [comment]
@vdubus Glad to hear it, thanks for the report.
